title: TU
email: taiyo7511@gmail.com

destination: _dist

baseurl: "" 
url: ""

github_username: taiyosilva

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
